### ISSUE TITLE
Missing README in pypi

### ISSUE THREAD

**Issue by asergeant01** [HunterMcGushion/docstr_coverage#1] opened 2019-01-25 11:45 UTC
On installing via tox, the following error is produced:

Complete output from command python setup.py egg_info:
--
25-Jan-2019 11:13:33 | Traceback (most recent call last):
25-Jan-2019 11:13:33 | File "<string>", line 1, in <module>
25-Jan-2019 11:13:33 | File "/tmp/pip-build-PBGljc/docstr-coverage/setup.py", line 19, in <module>
25-Jan-2019 11:13:33 | long_description=readme(),
25-Jan-2019 11:13:33 | File "/tmp/pip-build-PBGljc/docstr-coverage/setup.py", line 5, in readme
25-Jan-2019 11:13:33 | with open('README.md') as f:
25-Jan-2019 11:13:33 | IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by HunterMcGushion** [comment] 2019-01-25 19:58
@asergeant01,

Thank you for bringing this up. I don't have any experience with Tox yet (ridiculous, I know), but it looks like the problem was that I forgot to add a "MANIFEST.in" file to the project. 

Can you try to install the latest version (1.0.2), and let me know how it goes, please? Thanks for your help making the library better!

**Comment by asergeant01** [comment] 2019-01-28 08:07
Seems now its not including the actual package...

    from docstr_coverage.coverage import _execute
ModuleNotFoundError: No module named 'docstr_coverage'

It seems the find_packages isn't working.... If you specify it, i think it works
      packages=['docstr_coverage'],

**Comment by HunterMcGushion** [comment] 2019-01-28 16:41
I released v1.0.3 to PyPI after merging your PR and listing your bug-fix in CHANGELOG.md. 

I was able to install `docstr-coverage` under normal conditions, so can you please confirm that you're able to install via tox before we close the issue?

Thanks again for your PR (and for catching the bug in the first place)!

**Comment by HunterMcGushion** [comment] 2019-04-05 21:41
I'm going to close this issue, as it's been stale for a while, and as far as I can tell the problem has been fixed. @asergeant01, if this is not the case, please let me know, and we can revisit the issue!

**Closed by HunterMcGushion** 2019-04-05 21:41 UTC
Labels: bug

**Comment by killthekitten** [comment] 2020-05-26 10:05
@asergeant01 could you elaborate on how you encountered the `ModuleNotFoundError`? Were you running `tox` in a project where `docstr_coverage` is a dependency, or were you installing the library for local development?

In case of the latter, that would be an expected behavior. You can find more details in [this discussion](https://github.com/pytest-dev/pytest/issues/2287). The gist of it, install the library in a [development (or, editable) mode](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs):

```bash
pip install -e .
```
